name: Update AFCON Standings

on:
  schedule:
    # Morocco is UTC+1.
    - cron: '30 18,21 * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install axios cheerio firebase-admin @google/generative-ai

      - name: Run Update Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node update-standings.js